"""The per-profile conformance fixtures of RFC 0031 (SPEC §6.1), `conformance/profiles/<profile>/`: one
for every frozen profile, regenerated by `conformance/make_profiles.py` byte for byte; each record
verifies to the head in its `expected.json`, its line's canonical form and content hash recompute,
and `show`, `day --json` and `show days --json` print the files beside it."""

from __future__ import annotations

import filecmp
import importlib.util
import json
import shutil
from pathlib import Path
from types import ModuleType

import pytest

from logbook.core.chain import CONTENT_FIELDS, canonical_json, compute_hash, content_hash
from logbook.core.store import Logbook

ROOT = Path(__file__).resolve().parents[1]
PROFILES = ROOT / "conformance" / "profiles"
SCRIPT = ROOT / "conformance" / "make_profiles.py"


def _script() -> ModuleType:
    spec = importlib.util.spec_from_file_location("make_profiles", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _folders() -> list[Path]:
    return sorted(p for p in PROFILES.iterdir() if p.is_dir())


def test_every_frozen_profile_has_a_fixture_and_nothing_else_does() -> None:
    frozen = {profile.split("/")[0] for profile in _script().FROZEN}
    assert {p.name for p in _folders()} == frozen
    assert len(frozen) == 19


@pytest.mark.parametrize("folder", _folders(), ids=lambda p: p.name)
def test_the_record_verifies_to_its_head_and_the_line_recomputes(folder: Path) -> None:
    expected = json.loads((folder / "expected.json").read_text(encoding="utf-8"))
    lb = Logbook(folder / "record")
    seq, head, errors = lb.verify()
    assert (seq, head, errors) == (expected["seq"], expected["head"], [])
    (line,) = list(lb.lines())
    assert line["payload"]["schema"] == expected["profile"] and line["kind"] == expected["kind"]
    content = {k: line.get(k) for k in CONTENT_FIELDS}
    assert canonical_json(content) == expected["canonical"]
    assert content_hash(line) == expected["content_hash"]
    assert compute_hash(line) == expected["hash"] == line["hash"] == head


@pytest.mark.parametrize("folder", _folders(), ids=lambda p: p.name)
def test_show_day_and_days_print_the_fixture(folder: Path, tmp_path: Path) -> None:
    """On a copy (the readers build an index beside the record; the fixture never holds one)."""
    module = _script()
    expected = json.loads((folder / "expected.json").read_text(encoding="utf-8"))
    copy = tmp_path / "record"
    shutil.copytree(folder / "record", copy)
    day = expected["day"]
    assert module._run(copy, ["show", day]) == (folder / "show.txt").read_text(encoding="utf-8")
    assert module._run(copy, ["day", day, "--json"]) == (folder / "day.json").read_text(encoding="utf-8")
    assert module._run(copy, ["show", "days", "--from", day, "--to", day, "--json"]) == (
        folder / "days.json"
    ).read_text(encoding="utf-8")


def test_regenerating_reproduces_every_byte(tmp_path: Path) -> None:
    """`make_profiles.py` into a temp folder is the committed folder, file for file."""
    _script().main(tmp_path / "profiles")
    diff = filecmp.dircmp(PROFILES, tmp_path / "profiles")
    stale: list[str] = []

    def walk(d: filecmp.dircmp, prefix: str) -> None:
        stale.extend(f"{prefix}{name}" for name in d.left_only + d.right_only + d.diff_files + d.funny_files)
        for name, sub in d.subdirs.items():
            walk(sub, f"{prefix}{name}/")

    walk(diff, "")
    assert not stale, stale
