"""flight/v1 (RFC 0013): one flight the owner was on, seen by up to three producers.

This module is the one mapping every producer shares (ADR 0017). `build` makes a draft from the
fields a producer has; `parse_declaration` reads the owner's sentence (`logbook add flight "…"`);
the `flighty` adapter and `infer` (`logbook infer flights`) call `build` with what they read. `key`
is the flight's identity, `(date, carrier, number)`; `standing` finds the last line standing per key;
`merge` folds a new observation into the line that stands (rule 3: tracked over inferred over
declared, the declared role always); `reconcile` applies it to a stream of drafts before they are
appended.

Two small tables ship with the package under `logbook/tables/`: `airports.csv` (OurAirports, public
domain: IATA, ICAO, name, latitude, longitude and an IANA zone, regenerated by
`scripts/make_airports.py`) and `airlines.csv` (IATA and ICAO designators). A file named by
`--airports` or `LOGBOOK_AIRPORTS` adds to or overrides the airports. Nothing here touches the
network.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import math
import re
import zoneinfo
from collections.abc import Iterable, Iterator, Mapping
from datetime import UTC, date, datetime, timedelta
from functools import cache
from importlib import resources
from pathlib import Path
from typing import Any, NamedTuple
from zoneinfo import ZoneInfo

from .chain import Line
from .store import RETRACTION, Logbook, retractions

KIND = "flight"
SCHEMA = "flight/v1"
TIER = 1
AIRPORTS_ENV = "LOGBOOK_AIRPORTS"

EVIDENCE = ("declared", "inferred", "tracked")  # weakest first; the index is the rank
EVIDENCE_OF = {"flighty": "tracked", "flight-inference": "inferred", "manual": "declared"}
ROLES = ("passenger", "pilot")
TIMES = (
    "scheduled_departure",
    "actual_departure",
    "scheduled_takeoff",
    "actual_takeoff",
    "scheduled_landing",
    "actual_landing",
    "scheduled_arrival",
    "actual_arrival",
)
# Payload fields the merge decides one by one (rule 3); `role`, `evidence`, `observations`,
# `supersedes`, `raw_id` and the key have rules of their own.
MERGED = ("carrier_icao", "from", "to", "diverted_to", *TIMES, "aircraft", "cancelled", "extra")

NEAR_KM = 8.0  # a location point this close to an airport's reference point is at that airport
# The shortest time from the last point at one airport to the first at the next that can be a flight.
MIN_LEG = timedelta(minutes=20)
CELL_KM = 100.0  # up to this radius `nearest` searches the nine one-degree cells around a point
BEFORE = timedelta(hours=4)  # location points are searched this long before a calendar entry
AFTER = timedelta(hours=8)  # … and this long after its end (a delay, a long taxi, a late upload)
NO_END = timedelta(hours=6)  # an entry with no end is given this span
INFERENCE = "flight-inference"

Key = tuple[str, str, str]  # (date, carrier, number)


# -- airports ------------------------------------------------------------------------------------------


class Airport(NamedTuple):
    iata: str
    icao: str
    name: str
    lat: float
    lon: float
    tz: str


class Airports:
    """The airports table: by IATA or ICAO code, and the nearest to a point."""

    def __init__(self, rows: Iterable[Airport]):
        self._rows: list[Airport] = []
        self._by_code: dict[str, Airport] = {}
        self._cells: dict[tuple[int, int], list[Airport]] = {}  # by whole degree of (lat, lon)
        for airport in rows:
            self._add(airport)

    def _add(self, airport: Airport) -> None:
        previous = self._by_code.get(airport.iata)
        if previous is not None:  # an override replaces the built-in row
            self._rows.remove(previous)
            self._cells[_cell(previous.lat, previous.lon)].remove(previous)
            for code in (previous.iata, previous.icao):
                self._by_code.pop(code, None)
        self._rows.append(airport)
        self._cells.setdefault(_cell(airport.lat, airport.lon), []).append(airport)
        self._by_code[airport.iata] = airport
        if airport.icao:
            self._by_code[airport.icao] = airport

    @classmethod
    def load(cls, override: Path | None = None) -> Airports:
        """The built-in table, then the rows of `override` (same columns; `icao` and `name` may be
        absent) on top of it. A row without a code or coordinates, or with a zone the zone
        database does not know, is a ValueError naming its line."""
        airports = cls(_builtin_airports())
        if override is not None:
            text = Path(override).read_text(encoding="utf-8")
            for airport in _read_airports(text, str(override)):
                airports._add(airport)
        return airports

    def get(self, code: str) -> Airport | None:
        return self._by_code.get(code.strip().upper())

    def nearest(self, lat: float, lon: float, within_km: float = NEAR_KM) -> Airport | None:
        """The closest airport to a point, when one is within `within_km`."""
        best: Airport | None = None
        best_km = within_km
        for airport in self._near(lat, lon) if within_km <= CELL_KM else self._rows:
            km = distance_km(lat, lon, airport.lat, airport.lon)
            if km <= best_km:
                best, best_km = airport, km
        return best

    def _near(self, lat: float, lon: float) -> Iterator[Airport]:
        """The airports in the point's one-degree cell and the eight around it: every airport
        within a degree of latitude (111 km) and a degree of longitude, the longitude wrapping."""
        row, column = _cell(lat, lon)
        for d_row in (-1, 0, 1):
            for d_column in (-1, 0, 1):
                yield from self._cells.get((row + d_row, (column + d_column + 180) % 360 - 180), ())

    def __iter__(self) -> Iterator[Airport]:
        return iter(self._rows)

    def __len__(self) -> int:
        return len(self._rows)


def _cell(lat: float, lon: float) -> tuple[int, int]:
    return math.floor(lat), math.floor((lon + 180) % 360) - 180


@cache
def _builtin_airports() -> tuple[Airport, ...]:
    text = (resources.files("logbook") / "tables" / "airports.csv").read_text(encoding="utf-8")
    return tuple(_read_airports(text, "airports.csv"))


def _read_airports(text: str, name: str) -> list[Airport]:
    lines = [line for line in text.splitlines() if not line.startswith("#")]
    found: list[Airport] = []
    for n, row in enumerate(csv.DictReader(io.StringIO("\n".join(lines))), start=2):
        iata = (row.get("iata") or "").strip().upper()
        if not iata:
            raise ValueError(f"{name} line {n}: no iata code")
        tz = (row.get("tz") or "").strip()
        try:
            zoneinfo.ZoneInfo(tz)
        except (KeyError, ValueError, OSError):
            raise ValueError(f"{name} line {n}: unknown zone {tz!r}") from None
        try:
            lat, lon = float(row.get("lat") or ""), float(row.get("lon") or "")
        except ValueError:
            raise ValueError(f"{name} line {n}: lat and lon must be numbers") from None
        found.append(
            Airport(
                iata, (row.get("icao") or "").strip().upper(), (row.get("name") or "").strip(), lat, lon, tz
            )
        )
    return found


def distance_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance (haversine), in kilometres."""
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp, dl = math.radians(lat2 - lat1), math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * 6371.0 * math.asin(math.sqrt(a))


# -- airlines ---------------------------------------------------------------------------------------------


class Airlines:
    """IATA ↔ ICAO designators, so a carrier is spelled one way (RFC 0013 rule 1 and its note)."""

    def __init__(self, rows: Iterable[tuple[str, str]]):
        self._iata_of: dict[str, str] = {}
        self._icao_of: dict[str, str] = {}
        for iata, icao in rows:
            self._iata_of[icao] = iata
            self._iata_of[iata] = iata
            self._icao_of[iata] = icao

    @classmethod
    def load(cls) -> Airlines:
        return cls(_builtin_airlines())

    def iata(self, code: str) -> str:
        """The IATA designator for an IATA or ICAO code the table knows, else the code upper-cased."""
        code = code.strip().upper()
        return self._iata_of.get(code, code)

    def icao(self, code: str) -> str | None:
        return self._icao_of.get(self.iata(code))

    def knows(self, code: str) -> bool:
        return code.strip().upper() in self._iata_of


@cache
def _builtin_airlines() -> tuple[tuple[str, str], ...]:
    text = (resources.files("logbook") / "tables" / "airlines.csv").read_text(encoding="utf-8")
    lines = [line for line in text.splitlines() if not line.startswith("#")]
    return tuple(
        (row["iata"].strip().upper(), row["icao"].strip().upper())
        for row in csv.DictReader(io.StringIO("\n".join(lines)))
    )


# -- designators and routes in text --------------------------------------------------------------------------

DESIGNATOR = re.compile(r"(?<![A-Z0-9])([A-Z][A-Z0-9]|[0-9][A-Z]|[A-Z]{3})[ -]?(\d{1,4})([A-Z])?(?![A-Z0-9])")
FLIGHT_WORDS = ("flight", "flug", "✈")  # "flight", "Flug", ✈
CODE = re.compile(r"(?<![A-Z0-9])([A-Z]{3,4})(?![A-Z0-9])")


def designator(text: str, airlines: Airlines) -> tuple[str, str] | None:
    """(carrier, number) named in a calendar title: `LX 561`, `LX561`, `Flight to Zurich (LX 561)`.
    A code the airlines table knows is enough on its own; an unknown code counts only when the title
    says it is a flight ("flight", "Flug", ✈), so `Q3 review` and `Room 12` are not flights."""
    fallback: tuple[str, str] | None = None
    said_flight = any(word in text.lower() for word in FLIGHT_WORDS)
    for m in DESIGNATOR.finditer(text):
        code, digits, suffix = m.group(1), m.group(2), m.group(3) or ""
        number = f"{int(digits)}{suffix}"
        if airlines.knows(code):
            return airlines.iata(code), number
        if said_flight and fallback is None:
            fallback = code, number
    return fallback


def route_in(text: str, airports: Airports) -> tuple[str, str] | None:
    """The first two distinct airport codes the table knows, as IATA, in the order written."""
    found: list[str] = []
    for m in CODE.finditer(text):
        airport = airports.get(m.group(1))
        if airport is not None and airport.iata not in found:
            found.append(airport.iata)
        if len(found) == 2:
            return found[0], found[1]
    return None


def starts_with_designator(sentence: str) -> bool:
    """Whether the owner's sentence opens with a designator (`LX 561 …`, `LX561 …`), so that
    `add flight was delayed` stays a note and `add flight "LX 561 NCE ZRH …"` is a flight."""
    words = sentence.split()
    return bool(words) and (
        split_designator(words[0]) is not None
        or (len(words) > 1 and split_designator(" ".join(words[:2])) is not None)
    )


def split_designator(text: str) -> tuple[str, str] | None:
    """`LX561` or `LX 561` at the start of the owner's sentence, strictly."""
    m = re.fullmatch(r"([A-Z][A-Z0-9]|[0-9][A-Z]|[A-Z]{3})\s?0*(\d{1,4})([A-Z])?", text.strip().upper())
    if m is None:
        return None
    return m.group(1), f"{int(m.group(2))}{m.group(3) or ''}"


# -- the key and the draft --------------------------------------------------------------------------------


def key(payload: dict[str, Any]) -> Key:
    return str(payload.get("date")), str(payload.get("carrier")), str(payload.get("number"))


def key_text(k: Key) -> str:
    return ":".join(k)


def build(
    *,
    source: str,
    raw_id: str,
    airports: Airports,
    date: str,
    carrier: str,
    number: str,
    from_: dict[str, str],
    to: dict[str, str],
    carrier_icao: str | None = None,
    diverted_to: dict[str, str] | None = None,
    aircraft: dict[str, str] | None = None,
    role: str = "passenger",
    evidence: str | None = None,
    cancelled: bool | None = None,
    extra: dict[str, Any] | None = None,
    times: Mapping[str, str | None] | None = None,
) -> dict[str, Any]:
    """One flight/v1 draft (the envelope minus the chain fields) from a producer's fields. `times`
    maps RFC 0013 time fields to RFC3339 UTC (or None: absent). `evidence` defaults to the
    producer's (`EVIDENCE_OF`)."""
    times = times or {}
    unknown = set(times) - set(TIMES)
    if unknown:
        raise TypeError(f"not a flight/v1 time field: {', '.join(sorted(unknown))}")
    if role not in ROLES:
        raise ValueError(f"role must be one of {', '.join(ROLES)}, not {role!r}")
    evidence = evidence or EVIDENCE_OF[source]
    payload: dict[str, Any] = {
        "schema": SCHEMA,
        "raw_id": raw_id,
        "date": date,
        "carrier": carrier,
        "number": number,
    }
    if carrier_icao:
        payload["carrier_icao"] = carrier_icao
    payload["from"] = from_
    payload["to"] = to
    if diverted_to:
        payload["diverted_to"] = diverted_to
    for field in TIMES:
        value = times.get(field)
        if value:
            payload[field] = value
    if aircraft:
        payload["aircraft"] = aircraft
    payload["role"] = role
    if cancelled is not None:
        payload["cancelled"] = cancelled
    payload["evidence"] = evidence
    payload["observations"] = [{"evidence": evidence, "source": source}]
    if extra:
        payload["extra"] = extra
    return {**envelope(payload, airports), "source": source, "kind": KIND, "tier": TIER, "payload": payload}


def envelope(payload: dict[str, Any], airports: Airports) -> dict[str, Any]:
    """`at`, `end` and `tz` for a flight payload (RFC 0013 *Line*): the actual departure, else the
    scheduled, else local midnight of `date` at the origin (UTC midnight when its zone is unknown);
    the actual arrival, else the scheduled, else null; the origin's zone, else None (the record's)."""
    origin = _airport(payload.get("from"), airports)
    tz = origin.tz if origin is not None else None
    at = payload.get("actual_departure") or payload.get("scheduled_departure")
    if not at:
        at = local_to_utc(f"{payload['date']}T00:00", tz) if tz else f"{payload['date']}T00:00:00Z"
    end = payload.get("actual_arrival") or payload.get("scheduled_arrival") or None
    return {"at": at, "end": end, "tz": tz}


def _airport(ref: object, airports: Airports) -> Airport | None:
    if not isinstance(ref, dict):
        return None
    for code in (ref.get("iata"), ref.get("icao")):
        if isinstance(code, str) and code:
            airport = airports.get(code)
            if airport is not None:
                return airport
    return None


def airport_ref(code: str, airports: Airports) -> dict[str, str]:
    """`{iata, icao}` for a code the table knows; `{iata}` or `{icao}` for one it does not."""
    airport = airports.get(code)
    if airport is not None:
        ref = {"iata": airport.iata}
        if airport.icao:
            ref["icao"] = airport.icao
        return ref
    code = code.strip().upper()
    return {"icao": code} if len(code) == 4 else {"iata": code}


def local_to_utc(local: str, tz: str) -> str:
    """A wall-clock time (`2026-09-27T07:05`, seconds optional) in an IANA zone, as RFC 3339 UTC. A
    time that already carries `Z` or an offset is converted as it says."""
    text = local.strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    parsed = datetime.fromisoformat(text)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=ZoneInfo(tz))
    return parsed.astimezone(UTC).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")


def digest(*parts: object) -> str:
    """Twelve hex characters of the SHA-256 of the parts, for a `raw_id` suffix (rule 6)."""
    return hashlib.sha256(json.dumps(parts, sort_keys=True, ensure_ascii=False).encode()).hexdigest()[:12]


# -- the declaration ---------------------------------------------------------------------------------------

DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
CLOCK = re.compile(r"(\d{1,2}:\d{2})(?:-(\d{1,2}:\d{2}))?")
REGISTRATION = re.compile(r"(?:[A-Z0-9]{1,2}-[A-Z0-9]{2,5}|N\d{1,5}[A-Z]{0,2})")
DECLARATION_FORMAT = (
    'flight "<carrier> <number> <from> <to> <YYYY-MM-DD> [passenger|pilot] [HH:MM[-HH:MM]]'
    ' [type] [registration]", e.g. flight "LX 561 NCE ZRH 2026-09-27 pilot 07:05-08:20 A320 HB-JLT"'
)


def parse_declaration(text: str, airports: Airports, airlines: Airlines) -> dict[str, Any]:
    """The owner's sentence as a `manual` flight/v1 draft, evidence `declared` (RFC 0013). A sentence
    that does not fit the grammar is a ValueError that states it."""
    words = text.split()
    designator_ = None
    rest: list[str] = []
    if words:
        designator_ = split_designator(words[0])
        rest = words[1:]
        if designator_ is None and len(words) > 1:
            designator_ = split_designator(" ".join(words[:2]))
            rest = words[2:]
    if designator_ is None:
        raise ValueError(f"a flight starts with its designator, e.g. LX 561: {DECLARATION_FORMAT}")
    code, number = designator_
    if len(rest) < 3 or not (_is_code(rest[0]) and _is_code(rest[1])):
        raise ValueError(f"after the designator come the two airports and the date: {DECLARATION_FORMAT}")
    origin, destination = rest[0].upper(), rest[1].upper()
    if not DATE.fullmatch(rest[2]):
        raise ValueError(f"the date is YYYY-MM-DD, not {rest[2]!r}: {DECLARATION_FORMAT}")
    try:
        day = date.fromisoformat(rest[2])
    except ValueError:
        raise ValueError(f"{rest[2]!r} is not a calendar date: {DECLARATION_FORMAT}") from None
    role = "passenger"
    clocks: tuple[str, str | None] | None = None
    aircraft: dict[str, str] = {}
    for word in rest[3:]:
        lowered = word.lower()
        if lowered in ROLES:
            role = lowered
        elif (m := CLOCK.fullmatch(word)) is not None and clocks is None:
            clocks = m.group(1), m.group(2)
        elif REGISTRATION.fullmatch(word.upper()) and "registration" not in aircraft:
            aircraft["registration"] = word.upper()
        elif "type" not in aircraft and not CLOCK.fullmatch(word):
            aircraft["type"] = word
        else:
            raise ValueError(f"cannot place {word!r} in the flight: {DECLARATION_FORMAT}")
    carrier = airlines.iata(code)
    from_, to = airport_ref(origin, airports), airport_ref(destination, airports)
    times: dict[str, str | None] = {}
    extra: dict[str, Any] = {}
    if clocks is not None:
        departure, arrival = clocks
        origin_zone = (airports.get(origin) or Airport("", "", "", 0, 0, "")).tz
        destination_zone = (airports.get(destination) or Airport("", "", "", 0, 0, "")).tz
        _clock_field(
            "actual_departure", "departure_local", f"{day}T{_hhmm(departure)}", origin_zone, times, extra
        )
        if arrival is not None:
            local = f"{day}T{_hhmm(arrival)}"
            if destination_zone:
                arrived = local_to_utc(local, destination_zone)
                departed = times.get("actual_departure")
                if departed and arrived < departed:  # landed after midnight, the next local day
                    arrived = local_to_utc(f"{day + timedelta(days=1)}T{_hhmm(arrival)}", destination_zone)
                times["actual_arrival"] = arrived
            else:
                extra["arrival_local"] = local
    raw_id = f"{key_text((str(day), carrier, number))}@{digest(origin, destination, role, clocks, aircraft)}"
    return build(
        source="manual",
        raw_id=raw_id,
        airports=airports,
        date=str(day),
        carrier=carrier,
        number=number,
        carrier_icao=airlines.icao(code),
        from_=from_,
        to=to,
        aircraft=aircraft or None,
        role=role,
        extra=extra or None,
        times=times,
    )


def _is_code(word: str) -> bool:
    """An IATA (3) or ICAO (4) airport code."""
    return word.isalnum() and word.isascii() and len(word) in (3, 4)


def _hhmm(clock: str) -> str:
    hours, minutes = clock.split(":")
    if not (0 <= int(hours) < 24 and 0 <= int(minutes) < 60):
        raise ValueError(f"{clock!r} is not a time of day: {DECLARATION_FORMAT}")
    return f"{int(hours):02d}:{minutes}"


def _clock_field(
    field: str, local_field: str, local: str, tz: str, times: dict[str, str | None], extra: dict[str, Any]
) -> None:
    if tz:
        times[field] = local_to_utc(local, tz)
    else:
        extra[local_field] = local


# -- standing lines and the merge ------------------------------------------------------------------------


def standing(lines: Iterable[Line]) -> dict[Key, Line]:
    """The last flight line standing per key: not retracted, not superseded by another flight line."""
    lines = sorted(lines, key=lambda line: int(line["seq"]))
    retracted = retractions(line for line in lines if line.get("kind") == RETRACTION)
    live = [line for line in lines if line.get("kind") == KIND and str(line["id"]) not in retracted]
    superseded = {
        superseded
        for line in live
        if isinstance(superseded := (line.get("payload") or {}).get("supersedes"), str)
    }
    last: dict[Key, Line] = {}
    for line in live:
        if str(line["id"]) not in superseded:
            last[key(line["payload"])] = line
    return last


def rank(evidence: object) -> int:
    return EVIDENCE.index(str(evidence)) if evidence in EVIDENCE else -1


def merge(current: Line, new: dict[str, Any], airports: Airports | None = None) -> dict[str, Any]:
    """The draft that supersedes `current` with `new` folded in (RFC 0013 rule 3). The draft keeps
    `new`'s source and raw_id; the winner — the stronger evidence, the newer between equals — gives
    each field, the other fills what it lacks; a declared observation decides `role`; `evidence`
    is the strongest of all; the observations list grows by one."""
    airports = airports or Airports.load()
    old: dict[str, Any] = current["payload"]
    own: dict[str, Any] = new["payload"]
    own_evidence = str(own["evidence"])
    new_wins = rank(own_evidence) >= rank(old.get("evidence"))
    winner, loser = (own, old) if new_wins else (old, own)
    payload: dict[str, Any] = {
        "schema": SCHEMA,
        "raw_id": own["raw_id"],
        "date": own["date"],
        "carrier": own["carrier"],
        "number": own["number"],
    }
    for field in MERGED:
        if field == "extra":
            extra = {**(loser.get("extra") or {}), **(winner.get("extra") or {})}
            if extra:
                payload["extra"] = extra
        elif field in winner:
            payload[field] = winner[field]
        elif field in loser:
            payload[field] = loser[field]
    old_observations: list[dict[str, Any]] = [dict(o) for o in old.get("observations") or []]
    for observation in old_observations:
        observation.setdefault("line", str(current["id"]))
    if own_evidence == "declared":
        payload["role"] = own["role"]
    elif any(o.get("evidence") == "declared" for o in old_observations):
        payload["role"] = old.get("role", winner.get("role"))
    else:
        payload["role"] = winner.get("role", "passenger")
    observations = [*old_observations, *(own.get("observations") or [])]
    payload["evidence"] = max((str(o.get("evidence")) for o in observations), key=rank)
    payload["observations"] = observations
    payload["supersedes"] = str(current["id"])
    return {
        **envelope(payload, airports),
        "source": new["source"],
        "kind": KIND,
        "tier": max(int(current.get("tier", TIER)), int(new.get("tier", TIER))),
        "payload": payload,
    }


def reconcile(
    lb: Logbook,
    drafts: Iterable[dict[str, Any]],
    counts: dict[str, int] | None = None,
    airports: Airports | None = None,
) -> Iterator[dict[str, Any]]:
    """Pass drafts through; a flight draft whose key already stands in the record (or earlier in
    this stream) becomes the merged line that supersedes it. Every draft gets an id here so a later
    one in the same stream can name it. `counts["merged"]` tallies the merges. A draft that repeats
    an observation already in the stream (the same source and raw_id: four calendar entries for one
    flight give four identical inferences) is dropped, so what comes out is what `append_many`
    would write; one that repeats an observation already in the record is passed through for
    `append_many` to dedupe and report."""
    counts = counts if counts is not None else {}
    airports = airports or Airports.load()
    last: dict[Key, Line] | None = None
    seen: set[tuple[str, str]] = set()
    passed: set[tuple[str, str]] = set()
    for draft in drafts:
        if draft.get("kind") != KIND:
            yield draft
            continue
        if last is None:
            with lb.index() as idx:
                last = standing([*idx.by_kind(KIND), *idx.retractions()])
                seen = {
                    (str(line["source"]), str(line["payload"].get("raw_id"))) for line in idx.by_kind(KIND)
                }
        observation = (str(draft["source"]), str(draft["payload"].get("raw_id")))
        if observation in passed:
            continue  # the same observation earlier in this stream: the first one stands
        passed.add(observation)
        if observation in seen:
            yield draft  # an exact re-run of this observation: append_many dedupes it, nothing merges
            continue
        k = key(draft["payload"])
        current = last.get(k)
        if current is not None:
            draft = merge(current, draft, airports)
            counts["merged"] = counts.get("merged", 0) + 1
        draft.setdefault("id", _uuid7())
        last[k] = {**draft, "seq": 0}
        yield draft


def _uuid7() -> str:
    from .store import uuid7

    return uuid7()


# -- inference ---------------------------------------------------------------------------------------------


def infer(
    lb: Logbook,
    airports: Airports,
    since: str | None = None,
    until: str | None = None,
    counts: dict[str, int] | None = None,
) -> Iterator[dict[str, Any]]:
    """One `inferred` flight/v1 draft per calendar entry (`event/v1`, its last version standing, not
    cancelled) whose title names a flight and around which the record's location points leave one
    airport and next reach another (RFC 0013 *Producers*): a leg from the last point within NEAR_KM
    of one airport to the first point within NEAR_KM of a different one, every point between them
    (a tracker that keeps logging on the climb, or through the whole flight) near no airport, at
    least MIN_LEG long. Silence in between is usual but not required. `since` and `until` are
    local days that bound the entries considered. `counts` tallies `calendar_flights` (entries
    that name one) and `no_gap` (those the location points do not confirm)."""
    counts = counts if counts is not None else {}
    airlines = Airlines.load()
    with lb.index() as idx:
        events = idx.by_kind("event", since, until)
        retracted = retractions(idx.retractions())
        superseded = {s for e in events if isinstance(s := (e.get("payload") or {}).get("supersedes"), str)}
        for event in events:
            payload = event.get("payload") or {}
            if str(event["id"]) in retracted or str(event["id"]) in superseded:
                continue
            if payload.get("status") == "cancelled":
                continue
            named = designator(str(payload.get("title") or ""), airlines)
            if named is None:
                continue
            counts["calendar_flights"] = counts.get("calendar_flights", 0) + 1
            draft = _infer_one(event, named, idx, airports, airlines)
            if draft is None:
                counts["no_gap"] = counts.get("no_gap", 0) + 1
                continue
            yield draft


def _infer_one(
    event: Line, named: tuple[str, str], idx: Any, airports: Airports, airlines: Airlines
) -> dict[str, Any] | None:
    payload = event.get("payload") or {}
    all_day = bool(payload.get("all_day"))
    start = _instant(str(event["at"]))
    end = _instant(str(event["end"])) if event.get("end") else start + NO_END
    window = (start - BEFORE, end + AFTER) if not all_day else (start - BEFORE, end + BEFORE)
    places = idx.window(_stamp(window[0]), _stamp(window[1]))
    retracted = retractions(idx.retractions())
    points = [
        line
        for line in idx.read((p.file, p.offset) for p in places if p.kind == "location")
        if str(line["id"]) not in retracted and _coordinates(line) is not None
    ]
    points.sort(key=lambda line: (str(line["at"]), int(line["seq"])))
    hint = route_in(str(payload.get("title") or ""), airports)
    best: tuple[Line, Line, Airport, Airport] | None = None
    best_score: tuple[int, float] = (0, 0.0)
    last: tuple[Line, Airport] | None = None  # the latest point at an airport
    for point in points:
        lat, lon = _coordinates(point) or (0.0, 0.0)
        airport = airports.nearest(lat, lon)
        if airport is None:
            continue  # between airports: in the air, or on the ground somewhere else
        if last is not None and airport.iata != last[1].iata:
            before, origin = last
            after, destination = point, airport
            leg = _instant(str(after["at"])) - _instant(str(before["at"]))
            overlaps = _instant(str(after["at"])) >= start and _instant(str(before["at"])) <= end + BEFORE
            if leg >= MIN_LEG and (all_day or overlaps):  # the leg must overlap the entry, give or take
                matches = int(hint is not None and (origin.iata, destination.iata) == hint)
                score = (matches, leg.total_seconds())
                if score > best_score:
                    best, best_score = (before, after, origin, destination), score
        last = (point, airport)
    if best is None:
        return None
    before, after, origin, destination = best
    carrier, number = named
    times: dict[str, str | None] = {
        "actual_departure": str(before["at"]),
        "actual_arrival": str(after["at"]),
    }
    if not all_day:
        times["scheduled_departure"] = str(event["at"])
        times["scheduled_arrival"] = str(event["end"]) if event.get("end") else None
    departed = times["scheduled_departure"] if not all_day else times["actual_departure"]
    day = _instant(str(departed)).astimezone(ZoneInfo(origin.tz)).date().isoformat()
    k = (day, carrier, number)
    return build(
        source=INFERENCE,
        raw_id=f"{key_text(k)}@{times['actual_departure']}/{times['actual_arrival']}",
        airports=airports,
        date=day,
        carrier=carrier,
        number=number,
        carrier_icao=airlines.icao(carrier),
        from_=airport_ref(origin.iata, airports),
        to=airport_ref(destination.iata, airports),
        extra={"event": str(event["id"]), "gap": [str(before["id"]), str(after["id"])]},
        times=times,
    )


def _coordinates(line: Line) -> tuple[float, float] | None:
    payload = line.get("payload") or {}
    lat, lon = payload.get("lat"), payload.get("lon")
    if isinstance(lat, int | float) and isinstance(lon, int | float) and not isinstance(lat, bool):
        return float(lat), float(lon)
    return None


def _instant(stamp: str) -> datetime:
    return datetime.fromisoformat(stamp.replace("Z", "+00:00")).astimezone(UTC)


def _stamp(when: datetime) -> str:
    return when.astimezone(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
